/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { fetchAnalytics, RootState, AppDispatch } from "../redux/store.ts";
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import {
  Sparkles,
  AlertTriangle,
  Lightbulb,
  Layers,
  LineChart,
  BarChart3,
  PieChart as PieIcon,
  RefreshCw,
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

const COLORS = ["#10b981", "#3b82f6", "#8b5cf6", "#f59e0b", "#ec4899", "#14b8a6"];

export default function Analytics() {
  const dispatch = useDispatch<AppDispatch>();
  const { data: analytics, loading } = useSelector((state: RootState) => state.analytics);

  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  const [report, setReport] = useState<{
    executiveSummary: string;
    risks: string[];
    opportunities: string[];
    insights: string[];
  } | null>(null);

  useEffect(() => {
    dispatch(fetchAnalytics());
  }, [dispatch]);

  const handleGenerateExecutiveReport = async () => {
    setIsGeneratingReport(true);
    setReport(null);
    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: "Generate performance report and crm insights" }),
      });
      const data = await res.json();
      if (data.toolResult?.success) {
        setReport({
          executiveSummary: data.toolResult.executiveSummary,
          risks: data.toolResult.risks,
          opportunities: data.toolResult.opportunities,
          insights: data.toolResult.insights,
        });
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsGeneratingReport(false);
    }
  };

  const getCardValues = () => {
    if (!analytics) {
      return { interactions: 0, hcps: 0, pending: 0, products: 0 };
    }
    return {
      interactions: analytics.totals.interactions,
      hcps: analytics.totals.hcps,
      pending: analytics.totals.pendingFollowups,
      products: analytics.totals.products,
    };
  };

  const cardValues = getCardValues();

  return (
    <div id="analytics-page" className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl md:text-2xl font-bold text-white tracking-tight">CRM Analytics</h1>
          <p className="text-xs text-slate-400 mt-1">Real-time commercial insights and physician penetration metrics</p>
        </div>
        <button
          onClick={handleGenerateExecutiveReport}
          disabled={isGeneratingReport || loading}
          className="px-4 py-2.5 bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-400 hover:to-teal-500 disabled:from-slate-800 disabled:to-slate-900 text-slate-950 disabled:text-slate-500 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all shadow-lg shadow-emerald-500/10 cursor-pointer"
        >
          {isGeneratingReport ? (
            <>
              <RefreshCw className="w-4 h-4 animate-spin text-slate-950" />
              <span>Analyzing Territory Performance...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4 text-slate-950" />
              <span>Generate Executive AI Analysis</span>
            </>
          )}
        </button>
      </div>

      {/* AI Report Summary (Visible when generated) */}
      <AnimatePresence>
        {report && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="bg-white/5 backdrop-blur-2xl border border-emerald-500/15 rounded-2xl p-6 space-y-6 shadow-2xl"
          >
            {/* Report Header */}
            <div className="flex items-center gap-2 pb-3 border-b border-white/5">
              <Sparkles className="w-5 h-5 text-emerald-400" />
              <div>
                <h2 className="text-sm font-bold text-white uppercase tracking-wider">Executive CRM Intel Brief</h2>
                <p className="text-[10px] text-slate-400">Generated by LangGraph Analytical Agency Model</p>
              </div>
            </div>

            {/* Paragraph summary */}
            <div className="space-y-2">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wide block">Executive Summary</span>
              <p className="text-xs text-slate-200 leading-relaxed bg-black/25 p-4 rounded-xl border border-white/5 font-sans">
                {report.executiveSummary}
              </p>
            </div>

            {/* Grid for risks and opportunities */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2">
              {/* Opportunities */}
              <div className="space-y-3">
                <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wide flex items-center gap-1.5">
                  <Lightbulb className="w-4 h-4" />
                  Actionable Opportunities
                </span>
                <ul className="space-y-2.5">
                  {report.opportunities.map((opp, idx) => (
                    <li key={idx} className="text-xs text-slate-300 leading-relaxed flex items-start gap-2.5 bg-emerald-950/15 p-3 rounded-lg border border-emerald-500/10">
                      <span className="w-1.5 h-1.5 bg-emerald-400 rounded-full shrink-0 mt-1.5" />
                      <span>{opp}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Risks */}
              <div className="space-y-3">
                <span className="text-[10px] font-bold text-rose-400 uppercase tracking-wide flex items-center gap-1.5">
                  <AlertTriangle className="w-4 h-4" />
                  Barriers & Compliance Risks
                </span>
                <ul className="space-y-2.5">
                  {report.risks.map((risk, idx) => (
                    <li key={idx} className="text-xs text-slate-300 leading-relaxed flex items-start gap-2.5 bg-rose-950/15 p-3 rounded-lg border border-rose-500/10">
                      <span className="w-1.5 h-1.5 bg-rose-400 rounded-full shrink-0 mt-1.5" />
                      <span>{risk}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Core Insights */}
            <div className="pt-4 border-t border-white/5">
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wide block mb-3">Representative Insights</span>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {report.insights.map((insight, idx) => (
                  <div key={idx} className="bg-slate-900/40 border border-white/5 p-4 rounded-xl">
                    <span className="text-[10px] text-slate-400 font-mono font-bold block mb-1">METRIC INSIGHT {idx + 1}</span>
                    <p className="text-[11px] text-slate-300 leading-relaxed italic">"{insight}"</p>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* KPI Cards Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { title: "Total Meetings Logged", value: cardValues.interactions, sub: "High Touchpoints" },
          { title: "Territory Physicians", value: cardValues.hcps, sub: "Active Panel Size" },
          { title: "Action Items Pending", value: cardValues.pending, sub: "Urgent Tasks" },
          { title: "Formulary Products", value: cardValues.products, sub: "Therapeutics Approved" },
        ].map((item, i) => (
          <div key={i} className="bg-slate-950 border border-slate-800 rounded-xl p-4">
            <span className="text-[10px] uppercase font-semibold text-slate-500 tracking-wider block">{item.title}</span>
            <span className="text-2xl font-bold text-white mt-1 block">{item.value}</span>
            <span className="text-[9px] text-slate-400 font-medium block mt-1">{item.sub}</span>
          </div>
        ))}
      </div>

      {/* Charts Visualization Layout */}
      {loading ? (
        <div className="py-24 flex flex-col items-center justify-center space-y-2">
          <span className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" />
          <span className="text-xs text-slate-500">Generating chart configurations...</span>
        </div>
      ) : !analytics ? (
        <div className="py-24 text-center bg-slate-950 border border-slate-800 rounded-xl">
          <Layers className="w-12 h-12 text-slate-700 mx-auto mb-3" />
          <p className="text-sm text-slate-400 font-medium">No analytics datasets loaded</p>
          <p className="text-xs text-slate-500 mt-1">Interactions must be saved before chart distributions generate.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Chart 1: Area Trend (8 Columns) */}
          <div className="lg:col-span-8 bg-white/5 backdrop-blur-2xl border border-white/10 rounded-[24px] p-6 space-y-4">
            <div>
              <h2 className="text-xs font-bold uppercase tracking-widest text-slate-400 flex items-center gap-1">
                <LineChart className="w-4 h-4 text-emerald-400" />
                <span>Interactions Trend (7 Days)</span>
              </h2>
              <p className="text-[11px] text-slate-500">Weekly representative activity curve</p>
            </div>

            <div className="h-[280px]">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={analytics.weeklyTrend} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorInteractions" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#10b981" stopOpacity={0.25} />
                      <stop offset="95%" stopColor="#10b981" stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <XAxis dataKey="date" stroke="#475569" fontSize={10} tickLine={false} />
                  <YAxis stroke="#475569" fontSize={10} tickLine={false} />
                  <Tooltip
                    contentStyle={{ backgroundColor: "#0f172a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "8px" }}
                    labelStyle={{ color: "#94a3b8", fontSize: "11px" }}
                    itemStyle={{ color: "#fff", fontSize: "11px" }}
                  />
                  <Area type="monotone" dataKey="Interactions" stroke="#10b981" strokeWidth={2} fillOpacity={1} fill="url(#colorInteractions)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Chart 2: Pie distribution (4 Columns) */}
          <div className="lg:col-span-4 bg-white/5 backdrop-blur-2xl border border-white/10 rounded-[24px] p-6 space-y-4">
            <div>
              <h2 className="text-xs font-bold uppercase tracking-widest text-slate-400 flex items-center gap-1">
                <PieIcon className="w-4 h-4 text-indigo-400" />
                <span>Engagement Channels</span>
              </h2>
              <p className="text-[11px] text-slate-500">Breakdown of communication channels</p>
            </div>

            <div className="h-[200px] flex items-center justify-center relative">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={analytics.typesDistribution}
                    innerRadius={50}
                    outerRadius={75}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {analytics.typesDistribution.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{ backgroundColor: "#0f172a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "8px" }}
                    itemStyle={{ color: "#fff", fontSize: "11px" }}
                  />
                </PieChart>
              </ResponsiveContainer>
              <div className="absolute text-center">
                <span className="text-[10px] text-slate-500 uppercase tracking-widest block">Total</span>
                <span className="text-xl font-bold text-white block">{analytics.totals.interactions}</span>
              </div>
            </div>

            {/* Legend indicators */}
            <div className="grid grid-cols-2 gap-2 text-[10px] text-slate-400">
              {analytics.typesDistribution.map((item, idx) => (
                <div key={item.name} className="flex items-center gap-1.5">
                  <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: COLORS[idx % COLORS.length] }} />
                  <span className="truncate">{item.name} ({item.value})</span>
                </div>
              ))}
            </div>
          </div>

          {/* Chart 3: Products Discussed rates (12 Columns) */}
          <div className="lg:col-span-12 bg-white/5 backdrop-blur-2xl border border-white/10 rounded-[24px] p-6 space-y-4">
            <div>
              <h2 className="text-xs font-bold uppercase tracking-widest text-slate-400 flex items-center gap-1">
                <BarChart3 className="w-4 h-4 text-purple-400" />
                <span>Therapeutics Discussion Velocity</span>
              </h2>
              <p className="text-[11px] text-slate-500">Frequency of individual molecular products discussed in logged visits</p>
            </div>

            <div className="h-[250px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={analytics.productsDiscussed} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <XAxis dataKey="name" stroke="#475569" fontSize={10} tickLine={false} />
                  <YAxis stroke="#475569" fontSize={10} tickLine={false} />
                  <Tooltip
                    contentStyle={{ backgroundColor: "#0f172a", border: "1px solid rgba(255,255,255,0.1)", borderRadius: "8px" }}
                    labelStyle={{ color: "#94a3b8", fontSize: "11px" }}
                    itemStyle={{ color: "#fff", fontSize: "11px" }}
                  />
                  <Bar dataKey="count" fill="#8b5cf6" radius={[4, 4, 0, 0]}>
                    {analytics.productsDiscussed.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
